
# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost/full_stack
    username: postgres
    password: Admin
  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  # ===============================
  # = Email SMTP configurations
  # ===============================
  mail:
    host: smtp.gmail.com
    port: 587
    username: atalibcodinglevel@gmail.com
    password: vhvzdjilxriqrpyg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true